# Site Settings
title: My resume
url: 'https://kkedzierska.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Katarzyna Zofia Kedzierska
tagline: Visiting MSc Student @ Center for Public Health Genomics, UVa
pic: profile.jpg  # /assets/images/ 
summary: "My principal research interest lies in understanding the genetic and epigenetic influences over phenotypic changes in disease progressions, especially cancer. My solid experimental background allows me to investigate computational problems with thorough understanding of the underlying biology. I’m able to appreciate the complexity of the problems faced in the laboratory because of my degree in biotechnology, as well as my extensive experience in groups focused on genomic research. I was performing experiments followed by next-generation sequencing - RNA-seq, ChIP-seq, and ATAC-seq. My experience, especially with the later, resulted in an invitation to give a workshop at the #NGSchool - summer school in bioinformatics last September. In my work, I apply available methods and tools by tailoring them to my needs. I’m keen on developing new methods as well, like recently published SONiCS - a tool for genotyping short tandem repeats of which I was one of the developers."

#sidebar links
email: kzkedzierska@gmail.com
website: researchgate.net/profile/Katarzyna_Kedzierska #do not add http://
linkedin: kzkedzierska
github: kkedzierska
twitter: '@EthanePiroshki'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1
analytics: UA-109521177-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
